### ISSUE TITLE
Error when sending News-Information "Mails per session limit exceeded"

### ISSUE THREAD

**Issue by Caeppi** [engelsystem/engelsystem#1107]
Hello,
I am running the latest version from engelsystem on php8.1 and most of it is fine.

Yesterday, I wrote the first time an news to all costumers ans system is sending an information-mail to all of them, I think, I love this feature.
I am running it witch smtp mailer.

But in log, I can see, there is an error.
I understand, that there might be a limit at my provider, which is IONOS in germany.
I contactetd him allready.

But: I have only 45 members, so the system should only send 45 mails. I often send mails to over 100 peaple with no error.

Question: How is engelsystem sending mails? Is it one mail with x menbers, or 1 mail per 1 menber? Perhaps the second way should bypass the problem.

Or has anyone an other idea?

Thanx

<details>
<summary>Log</summary>

```
Sam (5): Unable to send email "notification.news.new" to user AB with Swift_TransportException: Expected response code 250 but got code "451", with message "451-Requested action aborted
451 Mails per session limit exceeded.
" in /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459
Stack trace:
#0 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(344): Swift_Transport_AbstractSmtpTransport->assertResponseCode('451-Requested a...', Array)
#1 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<helf...', Array, Array, true, NULL)
#2 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(386): Swift_Transport_EsmtpTransport->executeCommand('MAIL FROM:<helf...', Array, Array, true)
#3 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(485): Swift_Transport_EsmtpTransport->doMailFromCommand('helfer@mmc-berl...')
#4 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(518): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'helfer@mmc-berl...', Array, Array)
#5 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'helfer@mmc-berl...', Array, Array)
#6 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/Mailer.php(41): Swift_Mailer->send(Object(Swift_Message))
#8 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(104): Engelsystem\Mail\Mailer->send('ab@mmc-berlin.c...', '[MMC Helfersyst...', 'Hi AB,\nA new ne...')
#9 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(87): Engelsystem\Mail\EngelsystemMailer->send('ab@mmc-berlin.c...', '[MMC Helfersyst...', 'Hi AB,\nA new ne...')
#10 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(65): Engelsystem\Mail\EngelsystemMailer->sendView('ab@mmc-berlin.c...', 'New news: Schic...', 'emails/news-new', Array)
#11 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(68): Engelsystem\Mail\EngelsystemMailer->sendViewTranslated('ab@mmc-berlin.c...', 'New news: Schic...', 'emails/news-new', Array)
#12 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(51): Engelsystem\Events\Listener\News->sendMail(Object(Engelsystem\Models\News), Object(Engelsystem\Models\User\User), 'notification.ne...', 'emails/news-new')
#13 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(36): Engelsystem\Events\Listener\News->created(Object(Engelsystem\Models\News), 'news.created')
#14 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#16 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Engelsystem\Application), Array, Object(Closure))
#17 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(66): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), Array, Array)
#18 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(32): Illuminate\Container\BoundMethod::callClass(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#19 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#20 /hp/cm/ac/kf/www/mmc/helfer/src/Events/EventDispatcher.php(69): Illuminate\Container\Container->call('Engelsystem\\Eve...', Array)
#21 /hp/cm/ac/kf/www/mmc/helfer/src/helpers.php(105): Engelsystem\Events\EventDispatcher->dispatch('news.created', Array)
#22 /hp/cm/ac/kf/www/mmc/helfer/src/Controllers/Admin/NewsController.php(161): event('news.created', Array)
#23 [internal function]: Engelsystem\Controllers\Admin\NewsController->save(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#24 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(63): call_user_func_array(Array, Array)
#25 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(41): Engelsystem\Middleware\CallableHandler->execute(Array)
#26 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RequestHandler.php(52): Engelsystem\Middleware\CallableHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#27 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RequestHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#28 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SessionHandler.php(37): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#29 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SessionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#30 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RouteDispatcher.php(81): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#31 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RouteDispatcher->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#32 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/VerifyCsrfToken.php(38): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#33 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\VerifyCsrfToken->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#34 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ErrorHandler.php(63): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#35 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ErrorHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#36 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/AddHeaders.php(33): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#37 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\AddHeaders->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#38 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SetLocale.php(59): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#39 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SetLocale->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#40 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ExceptionHandler.php(40): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#41 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ExceptionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#42 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SendResponseHandler.php(25): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#43 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SendResponseHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#44 /hp/cm/ac/kf/www/mmc/helfer/public/index.php(19): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#45 {main}
Exception: Expected response code 250 but got code "451", with message "451-Requested action aborted
451 Mails per session limit exceeded.
"
File: /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459
Code: 451
Trace:
#0 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(344): Swift_Transport_AbstractSmtpTransport->assertResponseCode('451-Requested a...', Array)
#1 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<helf...', Array, Array, true, NULL)
#2 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(386): Swift_Transport_EsmtpTransport->executeCommand('MAIL FROM:<helf...', Array, Array, true)
#3 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(485): Swift_Transport_EsmtpTransport->doMailFromCommand('helfer@mmc-berl...')
#4 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(518): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'helfer@mmc-berl...', Array, Array)
#5 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'helfer@mmc-berl...', Array, Array)
#6 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/Mailer.php(41): Swift_Mailer->send(Object(Swift_Message))
#8 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(104): Engelsystem\Mail\Mailer->send('ab@mmc-berlin.c...', '[MMC Helfersyst...', 'Hi AB,\nA new ne...')
#9 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(87): Engelsystem\Mail\EngelsystemMailer->send('ab@mmc-berlin.c...', '[MMC Helfersyst...', 'Hi AB,\nA new ne...')
#10 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(65): Engelsystem\Mail\EngelsystemMailer->sendView('ab@mmc-berlin.c...', 'New news: Schic...', 'emails/news-new', Array)
#11 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(68): Engelsystem\Mail\EngelsystemMailer->sendViewTranslated('ab@mmc-berlin.c...', 'New news: Schic...', 'emails/news-new', Array)
#12 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(51): Engelsystem\Events\Listener\News->sendMail(Object(Engelsystem\Models\News), Object(Engelsystem\Models\User\User), 'notification.ne...', 'emails/news-new')
#13 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(36): Engelsystem\Events\Listener\News->created(Object(Engelsystem\Models\News), 'news.created')
#14 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#16 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Engelsystem\Application), Array, Object(Closure))
#17 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(66): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), Array, Array)
#18 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(32): Illuminate\Container\BoundMethod::callClass(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#19 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#20 /hp/cm/ac/kf/www/mmc/helfer/src/Events/EventDispatcher.php(69): Illuminate\Container\Container->call('Engelsystem\\Eve...', Array)
#21 /hp/cm/ac/kf/www/mmc/helfer/src/helpers.php(105): Engelsystem\Events\EventDispatcher->dispatch('news.created', Array)
#22 /hp/cm/ac/kf/www/mmc/helfer/src/Controllers/Admin/NewsController.php(161): event('news.created', Array)
#23 [internal function]: Engelsystem\Controllers\Admin\NewsController->save(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#24 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(63): call_user_func_array(Array, Array)
#25 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(41): Engelsystem\Middleware\CallableHandler->execute(Array)
#26 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RequestHandler.php(52): Engelsystem\Middleware\CallableHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#27 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RequestHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#28 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SessionHandler.php(37): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#29 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SessionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#30 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RouteDispatcher.php(81): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#31 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RouteDispatcher->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#32 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/VerifyCsrfToken.php(38): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#33 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\VerifyCsrfToken->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#34 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ErrorHandler.php(63): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#35 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ErrorHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#36 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/AddHeaders.php(33): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#37 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\AddHeaders->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#38 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SetLocale.php(59): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#39 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SetLocale->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#40 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ExceptionHandler.php(40): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#41 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ExceptionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#42 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SendResponseHandler.php(25): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#43 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SendResponseHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#44 /hp/cm/ac/kf/www/mmc/helfer/public/index.php(19): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#45 {main}
```

</details>

**Comment by msquare** [comment]
Hi,
thank you for reaching out. The engelsystem writes one separate e-mail per user.
The problem might be something something DNS: https://www.ionos.com/help/email/postmaster/smtp-error-messages-of-the-11-ionos-mail-servers/
Did you check that?

**Comment by Caeppi** [comment]
Thank you for your quick response.
Unfortunately, I can't find the exact error message there.
Number 451 is an other error.

I am using the smtp-Protokoll and the mailserver of IONOS für sending.

I thought, I can change from smtp to sendmail, but the engelsystem is running on an other server than the main domain, an other IP adress, so I think it could be rated as spam :-(

**Comment by Caeppi** [comment]
Additional: Or is it possible to tell the system to send the mails a little "slower". So, for example, taking a little break between emails?

**Comment by MyIgel** [comment]
Hmm, thats a good question.
As we are using the symfony mailer on the main branch you might eventually be able to set `email.driver` [dsn](https://symfony.com/doc/current/mailer.html#using-built-in-transports) to a [roundrobin](https://symfony.com/doc/current/mailer.html#load-balancing) config?
I have not tested that as i am currently on the way but eventually you could try that.

As an alternative doing some workarounds using a `sendmail` script wrapper on the host might work too.

**Comment by Caeppi** [comment]
Thanx for the answer, but I do not understand what to to.

I tryed sendmail, but this does noch work,

**Comment by MyIgel** [comment]
As we now have a new release, you might want to try that one as we replaced the mail component there.

The new mailer supports so-called dsn configs which should allow you to configre round robin (as in: using multiple hosts which means that the mails should hopefully get send via multiple connections):

```php
    'email'                   => [
        'driver' => 'roundrobin(smtps://[user]:[password]@smtp.ionos.com:465 smtps://[user]:[password]@smtp.ionos.com:465)',
    ],
```

you can there repeat the same `smtps://` sections for as many times as it might be needed.

**Comment by xuwhite** [comment]
If you have more questions or any problems please reopen this issue or create a new one.
