### ISSUE TITLE
Shifts can't be edited

### ISSUE THREAD

**Issue by bk-debug** [engelsystem/engelsystem#1111]
It's not possible to edit shifts

For a solution see PR #1112

Solution would be to add the line `use Engelsystem\Models\Room;` in `/var/www/includes/controllershifts_controller.php`
Log:

```admin (1): 
Exception: Class "Room" not found
File: /var/www/includes/controller/shifts_controller.php:70
Code: 0
Trace:
#0 /var/www/includes/pages/user_shifts.php(39): shift_edit_controller()
#1 /var/www/src/Middleware/LegacyMiddleware.php(109): user_shifts()
#2 /var/www/src/Middleware/LegacyMiddleware.php(57): Engelsystem\Middleware\LegacyMiddleware->loadPage('user_shifts')
#3 /var/www/src/Middleware/RouteDispatcher.php(48): Engelsystem\Middleware\LegacyMiddleware->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#4 /var/www/src/Middleware/Dispatcher.php(65): Engelsystem\Middleware\RouteDispatcher->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#5 /var/www/src/Middleware/VerifyCsrfToken.php(29): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#6 /var/www/src/Middleware/Dispatcher.php(65): Engelsystem\Middleware\VerifyCsrfToken->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#7 /var/www/src/Middleware/ErrorHandler.php(54): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#8 /var/www/src/Middleware/Dispatcher.php(65): Engelsystem\Middleware\ErrorHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#9 /var/www/src/Middleware/AddHeaders.php(24): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#10 /var/www/src/Middleware/Dispatcher.php(65): Engelsystem\Middleware\AddHeaders->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#11 /var/www/src/Middleware/SetLocale.php(43): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#12 /var/www/src/Middleware/Dispatcher.php(65): Engelsystem\Middleware\SetLocale->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#13 /var/www/src/Middleware/ExceptionHandler.php(31): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#14 /var/www/src/Middleware/Dispatcher.php(65): Engelsystem\Middleware\ExceptionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#15 /var/www/src/Middleware/SendResponseHandler.php(23): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#16 /var/www/src/Middleware/Dispatcher.php(65): Engelsystem\Middleware\SendResponseHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#17 /var/www/public/index.php(21): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#18 {main}```

**Comment by MyIgel** [comment]
Fixed by #1112
