### ISSUE TITLE
configuration of sendmail

### ISSUE THREAD

**Issue by Caeppi** [engelsystem/engelsystem#1190]
Hi again,
when trying to use sendmail in stead of smtps I am getting many erroirs.
Can please some help me to configure my sendmail?
Sendmail must be installes in Server (1blu), I am user iwnclod at the same system and it is working.

I Used xxx instaed of my personal files :-)

My configuration-file:
```
    // Email config
    'email'                   => [
        // Can be mail, smtp, sendmail or log
        'driver' => env('MAIL_DRIVER', 'smtp'),
        'from'   => [
            // From address of all emails
            'address' => env('MAIL_FROM_ADDRESS', 'xxx@xxx.com'),
            'name'    => env('MAIL_FROM_NAME', env('APP_NAME', 'xxx')),
        ],

        'host'       => env('MAIL_HOST', 'smtp.xxx.de'),
        'port'       => env('MAIL_PORT', 465),
        // Transport encryption like tls (for starttls) or ssl
        'encryption' => env('MAIL_ENCRYPTION', 'SSL'),
        'username'   => env('MAIL_USERNAME', 'xxx@xxx.com'),
        'password'   => env('MAIL_PASSWORD', 'xxx'),
        'sendmail'   => env('MAIL_SENDMAIL', '/usr/sbin/sendmail -bs'),
    ],
```

When changing 'smtp' to 'sendmail' I am getting this errors:
```
Patrick (2): Unable to send email "notification.news.new" to user Jonathan with Swift_TransportException: Expected response code 220 but got an empty response in /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:447
```

Stack trace:
<details>

```
#0 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(360): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)
#1 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#2 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(50): Swift_Transport_AbstractSmtpTransport->start()
#3 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_SendmailTransport->start()
#4 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/Mailer.php(41): Swift_Mailer->send(Object(Swift_Message))
#5 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(104): Engelsystem\Mail\Mailer->send('jonathan@mmc-be...', '[MMC Helfersyst...', 'Hi Jonathan,\nA ...')
#6 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(87): Engelsystem\Mail\EngelsystemMailer->send('jonathan@mmc-be...', '[MMC Helfersyst...', 'Hi Jonathan,\nA ...')
#7 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(65): Engelsystem\Mail\EngelsystemMailer->sendView('jonathan@mmc-be...', 'New news: asdad...', 'emails/news-new', Array)
#8 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(68): Engelsystem\Mail\EngelsystemMailer->sendViewTranslated('jonathan@mmc-be...', 'New news: asdad...', 'emails/news-new', Array)
#9 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(51): Engelsystem\Events\Listener\News->sendMail(Object(Engelsystem\Models\News), Object(Engelsystem\Models\User\User), 'notification.ne...', 'emails/news-new')
#10 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(36): Engelsystem\Events\Listener\News->created(Object(Engelsystem\Models\News), 'news.created')
#11 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Engelsystem\Application), Array, Object(Closure))
#14 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(66): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), Array, Array)
#15 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(32): Illuminate\Container\BoundMethod::callClass(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#16 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#17 /hp/cm/ac/kf/www/mmc/helfer/src/Events/EventDispatcher.php(69): Illuminate\Container\Container->call('Engelsystem\\Eve...', Array)
#18 /hp/cm/ac/kf/www/mmc/helfer/src/helpers.php(105): Engelsystem\Events\EventDispatcher->dispatch('news.created', Array)
#19 /hp/cm/ac/kf/www/mmc/helfer/src/Controllers/Admin/NewsController.php(161): event('news.created', Array)
#20 [internal function]: Engelsystem\Controllers\Admin\NewsController->save(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#21 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(63): call_user_func_array(Array, Array)
#22 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(41): Engelsystem\Middleware\CallableHandler->execute(Array)
#23 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RequestHandler.php(52): Engelsystem\Middleware\CallableHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#24 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RequestHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#25 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SessionHandler.php(37): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#26 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SessionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#27 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RouteDispatcher.php(81): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#28 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RouteDispatcher->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#29 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/VerifyCsrfToken.php(38): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#30 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\VerifyCsrfToken->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#31 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ErrorHandler.php(63): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#32 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ErrorHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#33 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/AddHeaders.php(33): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#34 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\AddHeaders->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#35 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SetLocale.php(59): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#36 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SetLocale->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#37 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ExceptionHandler.php(40): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#38 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ExceptionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#39 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SendResponseHandler.php(25): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#40 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SendResponseHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#41 /hp/cm/ac/kf/www/mmc/helfer/public/index.php(19): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#42 {main}
Exception: Expected response code 220 but got an empty response
File: /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:447
Code: 0
Trace:
#0 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(360): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)
#1 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#2 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(50): Swift_Transport_AbstractSmtpTransport->start()
#3 /hp/cm/ac/kf/www/mmc/helfer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_SendmailTransport->start()
#4 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/Mailer.php(41): Swift_Mailer->send(Object(Swift_Message))
#5 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(104): Engelsystem\Mail\Mailer->send('jonathan@mmc-be...', '[MMC Helfersyst...', 'Hi Jonathan,\nA ...')
#6 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(87): Engelsystem\Mail\EngelsystemMailer->send('jonathan@mmc-be...', '[MMC Helfersyst...', 'Hi Jonathan,\nA ...')
#7 /hp/cm/ac/kf/www/mmc/helfer/src/Mail/EngelsystemMailer.php(65): Engelsystem\Mail\EngelsystemMailer->sendView('jonathan@mmc-be...', 'New news: asdad...', 'emails/news-new', Array)
#8 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(68): Engelsystem\Mail\EngelsystemMailer->sendViewTranslated('jonathan@mmc-be...', 'New news: asdad...', 'emails/news-new', Array)
#9 /hp/cm/ac/kf/www/mmc/helfer/src/Events/Listener/News.php(51): Engelsystem\Events\Listener\News->sendMail(Object(Engelsystem\Models\News), Object(Engelsystem\Models\User\User), 'notification.ne...', 'emails/news-new')
#10 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(36): Engelsystem\Events\Listener\News->created(Object(Engelsystem\Models\News), 'news.created')
#11 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Engelsystem\Application), Array, Object(Closure))
#14 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(66): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), Array, Array)
#15 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/BoundMethod.php(32): Illuminate\Container\BoundMethod::callClass(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#16 /hp/cm/ac/kf/www/mmc/helfer/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(Engelsystem\Application), 'Engelsystem\\Eve...', Array, NULL)
#17 /hp/cm/ac/kf/www/mmc/helfer/src/Events/EventDispatcher.php(69): Illuminate\Container\Container->call('Engelsystem\\Eve...', Array)
#18 /hp/cm/ac/kf/www/mmc/helfer/src/helpers.php(105): Engelsystem\Events\EventDispatcher->dispatch('news.created', Array)
#19 /hp/cm/ac/kf/www/mmc/helfer/src/Controllers/Admin/NewsController.php(161): event('news.created', Array)
#20 [internal function]: Engelsystem\Controllers\Admin\NewsController->save(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#21 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(63): call_user_func_array(Array, Array)
#22 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/CallableHandler.php(41): Engelsystem\Middleware\CallableHandler->execute(Array)
#23 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RequestHandler.php(52): Engelsystem\Middleware\CallableHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#24 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RequestHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#25 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SessionHandler.php(37): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#26 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SessionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#27 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/RouteDispatcher.php(81): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#28 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\RouteDispatcher->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#29 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/VerifyCsrfToken.php(38): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#30 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\VerifyCsrfToken->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#31 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ErrorHandler.php(63): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#32 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ErrorHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#33 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/AddHeaders.php(33): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#34 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\AddHeaders->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#35 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SetLocale.php(59): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#36 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SetLocale->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#37 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/ExceptionHandler.php(40): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#38 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\ExceptionHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#39 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/SendResponseHandler.php(25): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#40 /hp/cm/ac/kf/www/mmc/helfer/src/Middleware/Dispatcher.php(80): Engelsystem\Middleware\SendResponseHandler->process(Object(Engelsystem\Http\Request), Object(Engelsystem\Middleware\Dispatcher))
#41 /hp/cm/ac/kf/www/mmc/helfer/public/index.php(19): Engelsystem\Middleware\Dispatcher->handle(Object(Engelsystem\Http\Request))
#42 {main}
```

</details>

**Comment by MyIgel** [comment]
Hi @Caeppi,
is there a reason to not directly use smtps? Anyhow, as the problems are caused by swiftmailer i guess you are using the v3.3.0 release?
We have replaced swiftmailer a while ago and its used in the newest release -> when you run the newest (v3.4.0) release the error messages might be a bit clearer.
btw,  i updated the formatting of your request a bit by using code tags so that it is easier readable ;)

**Comment by Caeppi** [comment]
OK, thanx for the information and help.
My Provider (ionos) does not support to send more than 20 mails at one time they said, so I can not use smtp. (see issue 1107), so I tryed to use sendmail.

I installed "clean" v3.4.0 on the same system, only registered one user (me) and wrote a news and I am getting an error:

admin (1): Unable to send email "notification.news.new" to user Patrick with Symfony\Component\Mailer\Exception\TransportException: Connection to "process /usr/sbin/sendmail -bs" has been closed unexpectedly. in /hp/cm/ac/kf/www/mmc/helfer-neu/vendor/symfony/mailer/Transport/Smtp/Stream/AbstractStream.php:84

Do I understand correctly, they closed sendmail?

**Comment by MyIgel** [comment]
That sounds more like `sendmail` itself is not supported by the hosting environment. Eventually you should directly use `'driver' => 'smtp',` there as written in the duplicated issue https://github.com/engelsystem/engelsystem/issues/1107 ?

**Comment by xuwhite** [comment]
@Caeppi Do you still have problems?

**Comment by MyIgel** [comment]
See also the "extended" "documentation" of https://github.com/engelsystem/engelsystem/issues/1403#issuecomment-2661420428

**Comment by xuwhite** [comment]
Because of inactivity I'll close this issue. If you have more questions or any problems please reopen this issue or create a new one.
