### ISSUE TITLE
c3nav embedding does not show marker

### ISSUE THREAD

**Issue by rugk** [engelsystem/engelsystem#711]
### STR

Go to https://engelsystem.de/36c3/rooms?action=view&room_id=23

### What happens

Looks like this:
![grafik](https://user-images.githubusercontent.com/11966684/71558468-0a7ff980-2a54-11ea-9767-f09ee7d64fd9.png)

### What should happen

Should display a marker, possibly?

## Also

* the "open in c3nav" link was a text (text cursor); when I dragged the map, it became a link)
* if I click that link through, it also just opens https://36c3.c3nav.de/@0,589.29,214.76,-0.46 i.e. a usual website

## System

Firefox 71
Fedora 31
GNOME

**Comment by MyIgel** [comment]
Currently it looks (for me) normal?

The entrance is not shown in c3nav as its not a publicly accessible entrance ;)

**Comment by rugk** [comment]
How normal? It should display me, where that is…

In "usual" c3nav it also does not work with any other location like the soulcharge area: https://engelsystem.de/36c3/rooms?action=view&room_id=2

**Comment by MyIgel** [comment]
With "normal" i mean it seems to work currently? So it should be a c3nav bug that got fixed ;)

**Comment by rugk** [comment]
No, it does not.

Screenshot from https://engelsystem.de/36c3/rooms?action=view&room_id=2

![grafik](https://user-images.githubusercontent.com/11966684/71723132-c615a480-2e2b-11ea-9dec-ba15839c33fa.png)

Please reopen this issue. :smile:

**Comment by MyIgel** [comment]
Nice, that seems to be a similar issues as we had on the camp (and works on my older firefox version just nice but not in chrome...)

```
output.edde0d2f8557.js:241 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at HTMLDocument.init (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:1475:2160)
    at mightThrow (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:230:18)
    at process (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:232:89)
(anonymous) @ output.edde0d2f8557.js:241
setTimeout (async)
jQuery.readyException @ output.edde0d2f8557.js:241
(anonymous) @ output.edde0d2f8557.js:241
mightThrow @ output.edde0d2f8557.js:230
process @ output.edde0d2f8557.js:232
setTimeout (async)
(anonymous) @ output.edde0d2f8557.js:235
fire @ output.edde0d2f8557.js:219
fireWith @ output.edde0d2f8557.js:225
fire @ output.edde0d2f8557.js:226
fire @ output.edde0d2f8557.js:219
fireWith @ output.edde0d2f8557.js:225
process @ output.edde0d2f8557.js:234
setTimeout (async)
(anonymous) @ output.edde0d2f8557.js:235
fire @ output.edde0d2f8557.js:219
fireWith @ output.edde0d2f8557.js:225
fire @ output.edde0d2f8557.js:226
fire @ output.edde0d2f8557.js:219
fireWith @ output.edde0d2f8557.js:225
ready @ output.edde0d2f8557.js:243
completed @ output.edde0d2f8557.js:243
output.edde0d2f8557.js:1601 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at NewClass.onAdd (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:1601:1811)
    at NewClass.addTo (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:951:147)
    at Object.init_map (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:1560:121)
    at Object.continue_init (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:1481:202)
    at Object._searchable_locations_loaded [as success] (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:1480:33)
    at fire (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:219:231)
    at Object.fireWith [as resolveWith] (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:225:181)
    at done (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:607:95)
    at XMLHttpRequest.<anonymous> (https://36c3.c3nav.de/static/CACHE/js/output.edde0d2f8557.js:620:300)
```

**Comment by rugk** [comment]
Ah oh sorry, forgot to look into the console. :man_facepalming: 

I do also have third-party cookies disabled.


And I get different console messages:
```
 Content Security Policy: Unbekannte Direktive 'defaul-src' kann nicht verarbeitet werden
13:51:28.717 updated fakedColorStatus via background script injection to Symbol(prefers-color-scheme: dark) f9ac8eea-04c7-43c8-bdce-fd2882be5fa2:4:29
13:51:28.773 set fakedColorStatus via content script to: Symbol(prefers-color-scheme: dark) common.js:16:13
13:51:28.901 Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. rooms
13:51:29.617 updated fakedColorStatus via background script injection to Symbol(prefers-color-scheme: dark) f9ac8eea-04c7-43c8-bdce-fd2882be5fa2:4:29
13:51:29.666 set fakedColorStatus via content script to: Symbol(prefers-color-scheme: dark) common.js:16:13
13:51:29.693
Anfrage für Zugriff auf Cookies oder Speicher für "<URL>" wurde blockiert, weil alle Anfragen für Speicherzugriff für nicht direkt aufgerufene Websites (Drittanbieter) blockiert werden und das Blockieren von Seitenelementen aktiviert ist. 3
13:51:29.694 Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. soulcharge
13:51:30.370 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://1c4e1215-d4b9-416b-ab35-3225e1fb2878/polyfills/browser-polyfill.min.js
Source-Map-Adresse: browser-polyfill.min.js.map

13:51:42.626
SecurityError: The operation is insecure. output.edde0d2f8557.js:formatted:16026
    init output.edde0d2f8557.js:16093
    mightThrow output.edde0d2f8557.js:2304
    process output.edde0d2f8557.js:2327
13:51:42.643 Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects für weitere Details und nehmen Sie an der Diskussion über damit verbundene Werkzeuge und Funktionen teil!
```
(If the debugger pauses at this breakpoint, the map does not finish loading)

and (console opened after map loaded)
```
 Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. soulcharge
13:52:47.316
Anfrage für Zugriff auf Cookies oder Speicher für "<URL>" wurde blockiert, weil alle Anfragen für Speicherzugriff für nicht direkt aufgerufene Websites (Drittanbieter) blockiert werden und das Blockieren von Seitenelementen aktiviert ist. 4
13:52:47.328
SecurityError: The operation is insecure. output.edde0d2f8557.js:formatted:16026
    init output.edde0d2f8557.js:16093
    mightThrow output.edde0d2f8557.js:2304
    process output.edde0d2f8557.js:2327
13:52:47.873
SecurityError: The operation is insecure. output.edde0d2f8557.js:formatted:17897
    onAdd output.edde0d2f8557.js:17954
    addTo output.edde0d2f8557.js:9612
    init_map output.edde0d2f8557.js:17302
    continue_init output.edde0d2f8557.js:16174
    _searchable_locations_loaded output.edde0d2f8557.js:16167
    fire output.edde0d2f8557.js:2103
    fireWith output.edde0d2f8557.js:2197
    done output.edde0d2f8557.js:6123
    callback output.edde0d2f8557.js:6300
13:52:49.515 Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://1c4e1215-d4b9-416b-ab35-3225e1fb2878/polyfills/browser-polyfill.min.js
Source-Map-Adresse: browser-polyfill.min.js.map

13:52:52.153 Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects für weitere Details und nehmen Sie an der Diskussion über damit verbundene Werkzeuge und Funktionen teil!
TypeError: c3nav._labelControl is undefined
output.edde0d2f8557.js:formatted:16325
    update_location_labels output.edde0d2f8557.js:16325
    _map_zoomed output.edde0d2f8557.js:17376
    fire output.edde0d2f8557.js:7125
    _moveEnd output.edde0d2f8557.js:9247
    _onZoomTransitionEnd output.edde0d2f8557.js:9578
    <anonym> self-hosted:875
```

**Comment by MyIgel** [comment]
Thats also shows the issue how [c3nav](https://github.com/c3nav/c3nav/issues) handles the localStorage/acces to permanent storage if its not allowed to do so ;)
So you should open an issue there and/or poke @codingcatgirl ^^

**Comment by rugk** [comment]
Done: https://github.com/c3nav/c3nav/issues/54
