### ISSUE TITLE
Exception: Undefined array key "description"

### ISSUE THREAD

**Issue by msquare** [engelsystem/engelsystem#854]
Gerade in den Logs gefunden:
```
Exception: Undefined array key "description"
File: /var/www/rc32021/includes/view/Shifts_view.php:180
Code: 0
Trace:
#0 /var/www/rc32021/includes/view/Shifts_view.php(180): Engelsystem\Exceptions\Handler->errorHandler()
#1 /var/www/rc32021/includes/controller/shifts_controller.php(317): Shift_view()
#2 /var/www/rc32021/includes/controller/shifts_controller.php(333): shift_controller()
```

**Comment by msquare** [comment]
Nevermind. This was due to missing migrations.
